### ISSUE TITLE
TopEntites not included in the EntityExtractionResponse

### ISSUE THREAD

**Issue by blairleighton** [giulioprinaricotti/dandelion-php#1]
Hi,

Thanks for the SDK it's great.  Just having an issue with the TopEntities, I can see they are not included in the EntityExtractionResponse.  I am not 100% up with swagger but I believe I need the definition swagger comments to regenerate this SDK.  Any chance this SDK could be updated to include the TopEntities in the response?

Have done it manually for now but obviously would be a lot better if all auto-generated.

Thanks

**Comment by giulioprinaricotti** [comment]
Sorry it took me so long. Should work as expected. Let me know if you need anything more and I'm really glad this was somewhat useful for you!
